# part 01 - 5 Simple Practical Tasks

### 1: create a Numpy array with value 1, 2, 3, 4

In [ ]:
import numpy as n

In [ ]:

arr = n.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

### 2: Create a 2D array with the values [[10,20],[30,40]]

In [5]:
arr2 = n.array([[10,20],[30,40]])
arr2

array([[10, 20],
       [30, 40]])

### 3: Create an array of 5 zeros using numpy 

In [8]:
# an array with 5 zeros using numpy 
zeros = n.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

### 4: Use np.arange() to create array from 0 to 9

In [11]:
arr3 = n.arange(9)
arr3 

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# part 2 - 5 Simple Questions 

### Qno1 : What does np.reshape() do?

### Ans: It changes the shape (dimensions) of a NumPy array without altering its underlying data. 

### Qno2: Write code to flatten: [[1,2],[3,4]] 

In [23]:
arr4 = n.array([[1,2],[3,4]])
print(arr4.flatten())



[1 2 3 4]


### Qno3: Which function joins two arrays ?

### Ans: np.concatenate()

### Qno4: Write code to get values greater than 10 from [5,15,20]


In [21]:
arr = [5,15,20]
arrgreaterthan10 = [x for x in arr if x > 10]
print(f"Original list: {arr}")
print(f"List with elements greater than 10: {arrgreaterthan10}")

Original list: [5, 15, 20]
List with elements greater than 10: [15, 20]


### Qno5: What does numpy.random.randint(1,5 size=3) do ?

### Ans: It generates an array of 3 random integers, each between 1 (inclusive) and 5 (exclusive).